[package]
name = "actix-web-plg"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
sqlx = { version = "0.7", features = [ "runtime-tokio", "sqlite" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1"
futures = "0.3"
env_logger = "0.10.0"
