name: Security Audit

run-name: ${{ github.actor }} is performing security audit.

# on:
#   push:
#     paths:
#       - '**/Cargo.toml'
#   schedule:
#     - cron: '0 0 * * *'

on:
  workflow_dispatch:
    logLevel:
      description: 'Log Level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug

jobs:
  audit:
    name: audit check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
