name: Build Rust Image

run-name: ${{ github.actor }} is building Docker image.

on:
  workflow_dispatch:
    logLevel:
      description: 'Log Level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/rust

jobs:
  rust:
    name: Build Rust Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@v3.1.1

      - name: Login to GitHub Container Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/rust
          push: true
          tags: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Sign the image with GitHub OIDC token
      #   env:
      #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
      #     TAGS: ${{ steps.meta.outputs.tags }}
      #   run: cosign sign --yes "${TAGS}@${DIGEST}"
