name: Test

run-name: ${{ github.actor }} is performing tests.

# on:
#   pull_request:
#     branches:
#       - main

on:
  workflow_dispatch:
    logLevel:
      description: 'Log Level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install sqlx-cli
        uses: baptiste0928/cargo-install@v2
        with:
          crate: sqlx-cli

      - run: mkdir -p data

      - name: Create Sqlite database
        run: sqlx database create

      - name: Run database migrations
        run: sqlx migrate run

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test
